# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesharesystem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
