# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0002_auto_20160718_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text=b'Lowercase slug identifying the city.', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.AlterModelOptions(
            name='bikesharesystem',
            options={'get_latest_by': 'last_update'},
        ),
        migrations.RemoveField(
            model_name='bikesharesystem',
            name='country',
        ),
        migrations.AddField(
            model_name='bikesharesystem',
            name='last_recorded_update',
            field=models.DateTimeField(help_text=b'Date and time at which an update was recorded on the bicycle sharing system. Null if this information is unavailable.', null=True),
        ),
    ]
