# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0003_auto_20160719_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='code',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='bikesharesystem',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshares.City'),
        ),
    ]
