# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0004_auto_20160725_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='active',
        ),
        migrations.AddField(
            model_name='bikesharesystem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
