# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0007_bikesharesystem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesharesystem',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bikesharesystem',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
