# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0008_auto_20160726_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_recorded_communication', models.DateTimeField(null=True)),
            ],
            options={
                'get_latest_by': 'last_recorded_communication',
            },
        ),
        migrations.CreateModel(
            name='StationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikes', models.IntegerField(help_text=b'Number of bicycles docked at that moment.')),
                ('free', models.IntegerField(help_text=b'Number of empty docks at that moment.')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(help_text=b'Date and time this update was recorded on the bicycle sharing system. Null if this information is unavailable.', null=True)),
                ('extra_data', models.TextField(help_text=b"Unparsed update data acquired from the city's bicycle sharing system.", null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshares.Station')),
            ],
            options={
                'get_latest_by': 'pk',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bikesharesystem',
            name='last_recorded_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='tag',
            field=models.SlugField(max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='bike_share_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshares.BikeShareSystem'),
        ),
    ]
