# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshares', '0009_auto_20160729_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationupdate',
            old_name='added_on',
            new_name='recorded_on',
        ),
    ]
